# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build project
      run: mvn compile
    - name: Build jar with dependencies
      run: |
        mvn compile assembly:single
        java -jar target/diffmin-1.0-SNAPSHOT-jar-with-dependencies.jar \
          src/test/resources/delete/literal/PREV_DeleteLiteral.java \
          src/test/resources/delete/literal/NEW_DeleteLiteral.java

  sorald-buildbreaker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Sorald Buildbreaker
        uses: SpoonLabs/sorald-buildbreaker@45bafb6
        with:
          source: 'src/main/java'

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Style check
      run: 'mvn spotless:check'
    - name: Verify if test resources compile
      run: ./scripts/verify-test-resource.sh
    - name: Run test phase
      run: mvn test
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
